apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waymo-dev
  namespace: aiea-slugbotics
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
