apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waymo-motion
  namespace: aiea-slugbotics
spec:
  storageClassName: seaweedfs-storage-nvme
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
