apiVersion: v1
kind: Pod
metadata:
  name: waymo-pod
  namespace: aiea-slugbotics
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/cuda.runtime.major
            operator: In
            values:
            - "12"
          - key: nvidia.com/cuda.driver.major
            operator: Gt
            values:
            - "535"
  containers:
  - name: vol-container
    # image: dakshshah/aiea-slugbotics:dev
    image: nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04
    command: ["sh", "-c", "sleep 10 && bash /pvcvolume/dev/setup_scripts/startup.sh"]
    resources:
      limits:
        memory: 32Gi
        cpu: "8"
        ephemeral-storage: "50Gi"
        nvidia.com/a100: "2"
      requests:
        memory: 16Gi
        cpu: "1"
        ephemeral-storage: "20Gi"
        nvidia.com/a100: "2"
    volumeMounts:
    # - mountPath: /pvcvolume/perception
    #   name: waymo-perception
    - mountPath: /pvcvolume/motion-rbd
      name: waymo-motion-rbd
    - mountPath: /pvcvolume/dev
      name: waymo-dev
    - mountPath: /pvcvolume/conda
      name: conda
  restartPolicy: Never
  volumes:
  - name: waymo-motion-rbd
    persistentVolumeClaim:
      claimName: waymo-motion-rbd 
  # - name: waymo-perception
  #   persistentVolumeClaim:
  #     claimName: waymo-perception
  - name: waymo-dev
    persistentVolumeClaim:
      claimName: waymo-dev
  - name: conda
    persistentVolumeClaim:
      claimName: conda