apiVersion: v1
kind: Pod
metadata:
  name: waymo-pod
  namespace: aiea-slugbotics
spec:
  containers:
  - name: vol-container
    image: ubuntu
    command: ["sh", "-c"]
    args: 
      - |
        apt-get update && apt --assume-yes upgrade
        apt --assume-yes install git wget curl gcc g++ make
        /pvcvolume/motion-rbd/conda/bin/conda init bash
        echo "conda activate waymo-env" >> ~/.bashrc
        source ~/.bashrc
        sleep infinity
    resources:
      limits:
        memory: 6Gi
        cpu: "8"
      requests:
        memory: 1Gi
        cpu: "1"
    volumeMounts:
    - mountPath: /pvcvolume/perception
      name: waymo-perception
    - mountPath: /pvcvolume/motion-rbd
      name: waymo-motion-rbd
    - mountPath: /pvcvolume/dev
      name: waymo-dev
  restartPolicy: Never
  volumes:
  - name: waymo-motion-rbd
    persistentVolumeClaim:
      claimName: waymo-motion-rbd
  - name: waymo-perception
    persistentVolumeClaim:
      claimName: waymo-perception
  - name: waymo-dev
    persistentVolumeClaim:
      claimName: waymo-dev