apiVersion: v1
kind: Pod
metadata:
  name: waymo-pod
spec:
  containers:
  - name: vol-container
    image: ubuntu
    command: ["sh", "-c", "apt-get update && apt --assume-yes install python3 git tmux vim && sleep infinity"]
    resources:
      limits:
        memory: 10Gi
        cpu: "10"
      requests:
        memory: 2Gi
        cpu: "2"
    volumeMounts:
    - mountPath: /pvcvolume/motion
      name: waymo-motion
    - mountPath: /pvcvolume/perception
      name: waymo-perception
    - mountPath: /pvcvolume/motion-rbd
      name: waymo-motion-rbd
  restartPolicy: Never
  volumes:
  - name: waymo-motion
    persistentVolumeClaim:
      claimName: waymo-motion
  - name: waymo-motion-rbd
    persistentVolumeClaim:
      claimName: waymo-motion-rbd
  - name: waymo-perception
    persistentVolumeClaim:
      claimName: waymo-perception