apiVersion: v1
kind: Pod
metadata:
  name: waymo-pod
  namespace: aiea-slugbotics
spec:
  containers:
  - name: vol-container
    image: dakshshah/aiea-slugbotics:dev
    command: ["sh", "-c", "sleep 10 && bash /pvcvolume/dev/setup_scripts/startup.sh"]
    resources:
      limits:
        memory: 6Gi
        cpu: "8"
        ephemeral-storage: "50Gi"
        # nvidia.com/gpu: "1"
      requests:
        memory: 1Gi
        cpu: "1"
        ephemeral-storage: "20Gi"
        # nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /pvcvolume/perception
      name: waymo-perception
    - mountPath: /pvcvolume/motion-rbd
      name: waymo-motion-rbd
    - mountPath: /pvcvolume/dev
      name: waymo-dev
    - mountPath: /pvcvolume/conda
      name: conda
  restartPolicy: Never
  volumes:
  - name: waymo-motion-rbd
    persistentVolumeClaim:
      claimName: waymo-motion-rbd 
  - name: waymo-perception
    persistentVolumeClaim:
      claimName: waymo-perception
  - name: waymo-dev
    persistentVolumeClaim:
      claimName: waymo-dev
  - name: conda
    persistentVolumeClaim:
      claimName: conda